### ISSUE TITLE
01.02.01 Add days of the week to a habit

### ISSUE THREAD

**Issue by JuliePilz** [CMPUT301F21T12/habitSmasher#4]
**User statement**
As a doer, I want a habit to have a plan for what days of the week it should regularly occur.

**Describe the solution you'd like**
Add a string of each day of the week, where selecting the day changes it color. See google calendar frequencies for reference. Add days of the week to habit.

### Things to consider
* How do we want to store the date in the database?

### UI mockup:
**Here is the view habit page where the dates will be shown:**
![image](https://user-images.githubusercontent.com/43623225/137219891-b926bbf7-4e3a-4ea8-8aa5-379b3d0c9351.png)

** Here is the add habit page where the dates can be selected:**
![image](https://user-images.githubusercontent.com/43623225/137220159-55a845e8-2e5f-4fed-9b83-4476f418830e.png)

**Development notes**
None yet

**Comment by aianta** [comment]
I'm a little unclear on the proposed solution here. You'll list the days of the week under reach habit and have the user tap? on the days it should occur? Can you add a screenshot of the google calendar example?
