### ISSUE TITLE
Add an ID field to Habit 

### ISSUE THREAD

**Issue by jaskim9824** [CMPUT301F21T12/habitSmasher#68]
When adding and querying habits in the database currently, we use the Habit Title as the title for the document holding the habit. This presents issues as though the title of the habit can change, the title of the document holding the habit cannot, which causes issues when attempting to query that habit. By adding a unique ID to each habit which cannot change and using that for the document title, it will make querying a habit a lot more easier.

**Comment by rudy-patel** [comment]
Completed
