### ISSUE TITLE
01.06.01 Restrict title and characters of habit

### ISSUE THREAD

**Issue by JuliePilz** [CMPUT301F21T12/habitSmasher#9]
**User statement**
As a doer, I want a habit title to be up to 20 characters and habit reason to be up to 30 characters.

**Describe the solution you'd like**
Add restrictions to title and reason of a given habit. 20 chars for title, 30 chars for reason

**Development notes**

**Comment by rudy-patel** [comment]
Won't do, included in with the habit creation story.
